In [4]:
import numpy as np 
import pandas as pd
import os
from scipy.linalg import solve
from shapely.geometry import Point, Polygon
import matplotlib.pyplot as plt

In [ ]:
Question 2

In [ ]:
# links for question 2 https://data.census.gov/table?q=population+of+united+states&tid=PEPPOP2019.PEPANNRES

In [5]:
os.chdir("C://Users//Admin//Desktop//Python ogallala")

In [12]:
fname = 'Population data.csv'
a = pd.read_csv(fname)
type(a)
a

,Geography (GEO_ID),Geographic Area Name (NAME),Estimate Date (DATE_CODE),Date Description (DATE_DESC),Population (POP)
0,0100000US,United States,1,4/1/2010 Census population,"308,745,538"
1,0100000US,United States,2,4/1/2010 population estimates base,"308,758,105"
2,0100000US,United States,3,7/1/2010 population estimate,"309,321,666"
3,0100000US,United States,4,7/1/2011 population estimate,"311,556,874"
4,0100000US,United States,5,7/1/2012 population estimate,"313,830,990"
5,0100000US,United States,6,7/1/2013 population estimate,"315,993,715"
6,0100000US,United States,7,7/1/2014 population estimate,"318,301,008"
7,0100000US,United States,8,7/1/2015 population estimate,"320,635,163"
8,0100000US,United States,9,7/1/2016 population estimate,"322,941,311"
9,0100000US,United States,10,7/1/2017 population estimate,"324,985,539"
10,0100000US,United States,11,7/1/2018 population estimate,"326,687,501"
11,0100000US,United States,12,7/1/2019 population estimate,"328,239,523"

In [ ]:
Question 3

In [10]:
def Deflectionwithq(q,L,E,I): #defining function to get deflection of beam with uniform load
    """L = length of cantilever
    I = moment of inertia
    E = modulus of elasticity;"""
    D1 = (q*L**4)/(8*E*I)
    return (D1)

In [ ]:
def Deflectionwith(L,E,I,F,a): #defining function to get deflection of beam with uniform load
    """L = length of cantilever
    I = moment of inertia
    E = modulus of elasticity;"""
    b = L - a
    D2=(F*a**3)/(8*E*I)*(1+3*a/2*b) 
    return (D2) # return the value